// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserRole } from './UserRole';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = number & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, UsersId | undefined, UsersId>;

  email: ColumnType<string, string, string>;

  password: ColumnType<string | null, string | null, string | null>;

  firstName: ColumnType<string, string, string>;

  lastName: ColumnType<string, string, string>;

  role: ColumnType<UserRole, UserRole | undefined, UserRole>;

  phone: ColumnType<string | null, string | null, string | null>;

  validate: ColumnType<boolean, boolean | undefined, boolean>;

  accessToken: ColumnType<string | null, string | null, string | null>;

  stripeCustomerId: ColumnType<string | null, string | null, string | null>;

  isSubscribed: ColumnType<boolean, boolean | undefined, boolean>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
